version: "3.9"

services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: "http://host.docker.internal:8080/api/v1"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:8080/api/v1
